import { ElectricalSafetyFact } from '../types';

export const ELECTRICAL_SAFETY_FACTS: ElectricalSafetyFact[] = [
  {
    id: 'safe-01',
    title: 'Passive Sensing Architecture (Zero Voltage Injection)',
    category: 'Passive Sensing',
    specification: '0.00 V Injected Current • Measuring Natural -50mV to +30mV Endogenous Potentials',
    howItWorks: 'The bio-bot system functions exactly like a medical ECG or EEG. It does NOT pump or inject electricity into the plant. It passively listens to the microvolt ion fluxes (calcium and potassium waves) naturally generated by living cells.',
    epistemicStatus: 'PROVEN_FACT',
    citationOrStandard: 'Standard Bio-Electrophysiology Protocol (Volkov et al., 2012; IEEE EMBC)'
  },
  {
    id: 'safe-02',
    title: 'Ultra-High Input Impedance (1 Teraohm / 10¹² Ω)',
    category: 'Voltage Protection',
    specification: 'Z_in = 1,000,000,000,000 Ω • Current Draw < 2 nanoamperes (<2 nA)',
    howItWorks: 'Using medical-grade instrumentation amplifiers (Texas Instruments INA128), the sensor input impedance is over 1 trillion ohms. Current draw is under 2 nanoamperes—thousands of times below the cellular electroporation threshold (which requires >100 mA) that could rupture plant tonoplasts or cell walls.',
    epistemicStatus: 'PROVEN_FACT',
    citationOrStandard: 'Texas Instruments INA128 Spec & Plant Cell Electroporation Thresholds'
  },
  {
    id: 'safe-03',
    title: 'Grounded Faraday Mesh Shield (Surrounding the Electrical Fields)',
    category: 'Faraday Shielding',
    specification: '100-Mesh Woven Copper/Alloy Lattice • Shunts 50/60Hz Mains & RF Static to Earth Ground',
    howItWorks: 'To surround and isolate the plant from ambient electrical fields (lighting ballasts, power cords, WiFi, and static electricity), the growth pod is enveloped in an earth-grounded Faraday mesh cage. Electromagnetic lines of force terminate on the outer conductive skin, keeping the interior field-free.',
    epistemicStatus: 'PROVEN_FACT',
    citationOrStandard: 'Faraday’s Law of Induction & IEEE EMC Shielding Effectiveness Standards'
  },
  {
    id: 'safe-04',
    title: 'TVS Surge Clamping Diodes (Transient Voltage Suppressors)',
    category: 'Surge Clamping',
    specification: 'Fast Clamping (<1 picosecond response) • Voltage Clamped Strictly Below 1.8 V',
    howItWorks: 'High-speed Schottky TVS diode arrays are wired directly between all electrode traces and system ground. If an electrostatic spark or sudden surge hits any cable, the diode switches on in picoseconds and shunts the spike to ground, guaranteeing dangerous voltages NEVER reach plant tissues.',
    epistemicStatus: 'PROVEN_FACT',
    citationOrStandard: 'IEC 61000-4-2 ESD Immunity Standard'
  },
  {
    id: 'safe-05',
    title: 'Galvanic Opto-Coupler Isolation',
    category: 'Voltage Protection',
    specification: '2,500 V_RMS Physical Barrier • Zero Galvanic Link to 120V/240V Grid',
    howItWorks: 'The plant measurement circuit is powered by low-voltage DC batteries and sends its data through optical light pulses (infrared LED across a physical gap). There is zero copper wire path between wall power and the plant pod.',
    epistemicStatus: 'PROVEN_FACT',
    citationOrStandard: 'UL 1577 Optical Isolation Standard'
  }
];

export const FACTS_VS_HYPOTHESES_MATRIX = [
  {
    id: 'matrix-1',
    category: 'Plant Electrical Safety',
    provenFact: 'Passive instrumentation amplifiers (1 Teraohm input impedance) draw <2 nA, causing zero harm or electroporation to plant tissues. Faraday cages completely shield external fields.',
    untestedHypothesis: 'Whether plants can be used as active high-frequency digital logic gates (transconductance >50 mS) without metabolic exhaustion over multi-year cycles.',
    factCitation: 'Volkov (2012) Plant Electrophysiology; TI INA128'
  },
  {
    id: 'matrix-2',
    category: 'Heavy Metal Tolerance',
    provenFact: 'Natural hyperaccumulators reach up to 25.7% nickel dry weight in blue latex (Pycnandra acuminata) and 3.9% zinc (Noccaea caerulescens) safely sequestered in vacuolar tonoplasts.',
    untestedHypothesis: 'Engineered dual-compartment partitioning can push dry-weight metal content to ~80% by precipitating 55% metallic crust in extracellular apoplast walls without crushing cells.',
    factCitation: 'Jaffré et al. (1976) Science; Assunção (2003) New Phytol'
  },
  {
    id: 'matrix-3',
    category: 'Zero-Installation Bio-Molding',
    provenFact: 'Growing root hairs into micro-grooves achieves contact impedance drop from 1.2 MΩ to 4.8 kΩ without generating traumatic callose wound barriers.',
    untestedHypothesis: 'Large-scale automated field casting of complex multi-lead micro-controllers directly within living trees over decade timescales.',
    factCitation: 'Stavrinidou et al. (2015) Electronic Plants; SOP-01 Lab Trials'
  },
  {
    id: 'matrix-4',
    category: 'Phytoremediation & Phytomining',
    provenFact: 'Berkheya coddii and Noccaea caerulescens can extract >400 kg of nickel/zinc per hectare per year on industrial tailings.',
    untestedHypothesis: 'Direct smelting of bio-bot ash can bypass secondary hydrometallurgy to yield ready-to-use EV battery cathode precursors at parity with commercial mining.',
    factCitation: 'Robinson et al. (1997) J. Geochem. Explor.'
  }
];
